---
- name: Managed Local Configuration
  hosts: local
  tasks:
    - name: Configure SSH access for {{ host_alias }}
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        marker: "# {mark} {{ host_alias }} ANSIBLE MANAGED BLOCK"
        create: yes
        mode: "0600"
        block: |
          Host {{ host_alias }}
              HostName {{ ip }}
              User {{ user }}
              Port 22
