// Deploy keys, and the GitHub environment they are published to.
//
// This is a sixth concern rather than a step in `tools`: nothing here renders a
// template or drives OpenTofu or Ansible, and the credentials it moves belong
// to a service outside the stack entirely.
//
// An application naming a repository gets its own keypair on every create. The
// public half is installed on the box behind a ForceCommand restricted to that
// one host, and the private half is published to a GitHub Actions environment
// named after the profile. Nothing is stored: the keys are regenerated next
// create, which is affordable because the ForceCommand means a leaked key can
// trigger a redeploy of one application and nothing else.
//
// Keys are generated by `ssh-keygen` rather than in process. Three languages
// agreeing on OpenSSH private-key encoding is a parity problem; one subprocess
// is not.
//
// The private key is never passed as an argument. The runtime seam spawns with
// `stdin: "ignore"`, so it cannot be piped either — instead the key stays in
// the 0600 file `ssh-keygen` wrote and `gh` reads it through a shell redirect,
// so it stays out of the process table the same way stdin would have kept it.

import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runtime, type ExecResult } from "red/runtime";
import type { Opts } from "red/workflow";
import { githubApplications } from "./validate.ts";

const runTimeoutMs = 30000;

export type Runner = (cmd: string[], opts?: { env?: Record<string, string | undefined>; timeoutMs?: number }) => Promise<ExecResult>;

const defaultRunner: Runner = (cmd, opts = {}) => runtime.exec(cmd, { ...opts, timeoutMs: opts.timeoutMs ?? runTimeoutMs });

// The public key a build renders. Generation is a create-time side effect, so
// build and dry-run need a value that never changes — a fresh key every build
// would make the rendered artifact nondeterministic and break byte parity.
const placeholderPublic = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUILDPLACEHOLDER0000000000000000000000";

export interface DeployKey {
  host: string;
  github?: string;
  public: string;
  privateFile?: string;
}

// Identifies a key on the box. Carries no timestamp: the comment is rendered
// into the artifact, and a clock reading there would break byte parity.
// Ordering for retention comes from position in authorized_keys instead.
export function keyComment(opts: Opts, host: string): string {
  return `once-deploy-${opts.profile ?? "default"}-${host}`;
}

export function placeholderKeys(opts: Opts): DeployKey[] {
  return githubApplications(opts).map((app) => ({
    host: String(app.host),
    github: app.github ? String(app.github) : undefined,
    public: `${placeholderPublic} ${keyComment(opts, String(app.host))}`,
  }));
}

function keygenArgs(opts: Opts, host: string, path: string): string[] {
  return ["ssh-keygen", "-t", "ed25519", "-N", "", "-q", "-C", keyComment(opts, host), "-f", path];
}

// Generate one keypair per application naming a repository, into a private
// directory. Returns the keys and an error; the keys carry the public half
// inline and the private half only as a path, so the secret never enters opts.
export async function generateKeys(
  opts: Opts,
  runFn: Runner = defaultRunner,
): Promise<[DeployKey[], string | undefined]> {
  const apps = githubApplications(opts);
  if (!apps.length) return [[], undefined];
  const dir = mkdtempSync(join(tmpdir(), "once-deploy"));
  const keys: DeployKey[] = [];
  for (const [index, app] of apps.entries()) {
    const path = join(dir, `key-${index}`);
    const result = await runFn(keygenArgs(opts, String(app.host), path), {});
    if (result.exit !== 0) {
      return [[], `ssh-keygen failed for ${app.host}: ${String(result.err ?? "").trim()}`];
    }
    keys.push({
      host: String(app.host),
      github: String(app.github),
      public: readFileSync(`${path}.pub`, "utf8").trim(),
      privateFile: path,
    });
  }
  return [keys, undefined];
}

// The render-facing view: host and public key only. `tools` builds the
// authorized_keys lines from this, so no private key can reach a template.
export function publicKeys(opts: Opts): Array<{ host: string; public: string }> {
  const keys = (opts["once/deploy-keys"] as DeployKey[] | undefined) ?? [];
  return keys.map(({ host, public: pub }) => ({ host, public: pub }));
}

// ------------------------------------------------------------- the gh commands

export interface Command {
  label: string;
  args: string[];
}

function envName(opts: Opts): string {
  return String(opts.profile ?? "default");
}

function shellQuote(value: unknown): string {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

// Read the server's own SSH host key over the administrative connection, so a
// workflow can pin it instead of running ssh-keyscan on every deploy.
//
// This is still trust on first use — nothing here has a prior binding for that
// key either. What it changes is the window: CI stops asking the network who
// the server is on every single deploy, and starts comparing against a value
// captured once, so a substituted key is detected from then on.
export function hostKeyArgs(opts: Opts): string[] {
  return [
    "ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10",
    "-o", "StrictHostKeyChecking=accept-new",
    `${opts.user ?? "root"}@${opts.ip}`,
    "cat /etc/ssh/ssh_host_ed25519_key.pub",
  ];
}

// A known_hosts entry from an ssh_host_*.pub file's contents. The trailing
// comment is dropped: it is the server's own hostname at key generation time
// and means nothing to a client.
export function knownHostsLine(ip: unknown, pub: unknown): string | undefined {
  const [algo, body] = String(pub ?? "").trim().split(/\s+/);
  if (!algo || !body || !algo.startsWith("ssh-")) return undefined;
  return `${ip} ${algo} ${body}`;
}

// A failure here is not fatal: the credentials are still worth publishing, and
// a workflow that finds no SSH_KNOWN_HOSTS can say so itself.
export async function fetchHostKey(opts: Opts, runFn: Runner): Promise<string | undefined> {
  const result = await runFn(hostKeyArgs(opts), {});
  return result.exit === 0 ? knownHostsLine(opts.ip, result.out) : undefined;
}

// The ip and user are variables rather than secrets: DNS already reveals the
// address, and masking them only makes CI logs harder to read.
//
// The environment is created first, with an idempotent PUT. A workflow that
// names an environment does bring it into being, which would have kept this
// token off admin scope — but that only helps once the workflow has been wired
// to the environment, and nothing here can guarantee that came first. Writing
// into an environment that does not exist is a 404, so ONCE creates it.
export function publishCommands(opts: Opts, key: DeployKey): Command[] {
  const env = envName(opts);
  const repo = String(key.github);
  const base = ["--repo", repo, "--env", env];
  return [
    { label: `${repo} environment ${env}`, args: ["gh", "api", "--method", "PUT", "--silent", `repos/${repo}/environments/${env}`] },
    { label: `${repo} SERVER_IP`, args: ["gh", "variable", "set", "SERVER_IP", ...base, "--body", String(opts.ip)] },
    { label: `${repo} SERVER_USER`, args: ["gh", "variable", "set", "SERVER_USER", ...base, "--body", "deploy"] },
    { label: `${repo} SSH_KNOWN_HOSTS`, args: ["gh", "variable", "set", "SSH_KNOWN_HOSTS", ...base, "--body", String(opts["once/known-hosts"] ?? "")] },
    {
      label: `${repo} SSH_PRIVATE_KEY`,
      args: [
        "sh",
        "-c",
        `gh secret set SSH_PRIVATE_KEY --repo ${shellQuote(repo)} --env ${shellQuote(env)} < ${shellQuote(key.privateFile)}`,
      ],
    },
  ];
}

// Delete needs no key material, so this works with the box already destroyed —
// which is why it runs before teardown rather than after.
export function revokeCommands(opts: Opts, key: { github?: unknown }): Command[] {
  const env = envName(opts);
  const repo = String(key.github);
  const base = ["--repo", repo, "--env", env];
  return [
    { label: `${repo} SERVER_IP`, args: ["gh", "variable", "delete", "SERVER_IP", ...base] },
    { label: `${repo} SERVER_USER`, args: ["gh", "variable", "delete", "SERVER_USER", ...base] },
    { label: `${repo} SSH_KNOWN_HOSTS`, args: ["gh", "variable", "delete", "SSH_KNOWN_HOSTS", ...base] },
    { label: `${repo} SSH_PRIVATE_KEY`, args: ["gh", "secret", "delete", "SSH_PRIVATE_KEY", ...base] },
  ];
}

export function commands(opts: Opts): Command[] {
  const isDelete = opts["red/event"] === "delete";
  if (isDelete) return githubApplications(opts).flatMap((app) => revokeCommands(opts, app));
  const keys = (opts["once/deploy-keys"] as DeployKey[] | undefined) ?? [];
  return keys.flatMap((key) => publishCommands(opts, key));
}

// ------------------------------------------------------------------- the step

function cleanup(opts: Opts): Opts {
  const dir = opts["once/key-dir"];
  if (typeof dir === "string") rmSync(dir, { recursive: true, force: true });
  const keys = (opts["once/deploy-keys"] as DeployKey[] | undefined) ?? [];
  const { "once/key-dir": _dropped, ...rest } = opts;
  return { ...rest, "once/deploy-keys": keys.map(({ privateFile: _p, ...key }) => key) };
}

// Publish on create, revoke on delete, do nothing otherwise.
//
// `wireFn` runs the same branch for build and create, so the event check here
// is what keeps a build from reaching GitHub; `sideEffectingSteps` only covers
// `--dry-run`.
//
// A revoke that fails because there is nothing to revoke is not an error:
// delete has to be re-runnable, and a missing secret is the state it is trying
// to reach.
export async function githubStep(opts: Opts, runFn: Runner = defaultRunner): Promise<Opts> {
  const event = String(opts["red/event"]);
  if (event !== "create" && event !== "delete") return opts;
  const isDelete = event === "delete";
  if (!isDelete && githubApplications(opts).length) {
    opts = { ...opts, "once/known-hosts": await fetchHostKey(opts, runFn) };
  }
  const env = { GH_TOKEN: String(opts["github-token"] ?? "") };
  let failure: string | undefined;
  for (const { args, label } of commands(opts)) {
    const result = await runFn(args, { env });
    if (result.exit !== 0 && !isDelete) {
      failure = `gh failed for ${label}: ${String(result.err ?? "").trim()}`;
      break;
    }
  }
  const cleaned = cleanup(opts);
  return failure ? { ...cleaned, "red/exit": 1, "red/err": failure } : { ...cleaned, "red/exit": 0 };
}
