#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# One fixture, three colours. Feeding the same colors.yml to all of them is
# the point: three files describing "the same" desired state could drift apart
# and quietly weaken every comparison below.
state="$root/test/parity/colors.yml"

build_variant() {
  local variant=$1
  shift
  (
    cd "$root/green"
    env COLORS_PAR_WORKDIR="$tmp/$variant/green" "$@" bb green build -f "$state" >/dev/null
  )
  (
    cd "$root/red"
    env COLORS_PAR_WORKDIR="$tmp/$variant/red" "$@" ./red build -f "$state" >/dev/null
  )
  (
    cd "$root/blue"
    env COLORS_PAR_WORKDIR="$tmp/$variant/blue" "$@" uv run python -m package_once_blue build -f "$state" >/dev/null
  )
  diff -qr "$tmp/$variant/green/parity" "$tmp/$variant/red/parity"
  diff -qr "$tmp/$variant/green/parity" "$tmp/$variant/blue/parity"
}

build_variant local
build_variant digitalocean-vpc COLORS_PAR_DIGITALOCEAN_VPC_UUID=vpc-123
build_variant hcloud COLORS_PAR_PROVIDER_COMPUTE=hcloud
build_variant yandex COLORS_PAR_PROVIDER_COMPUTE=yandex
build_variant oci COLORS_PAR_PROVIDER_COMPUTE=oci
build_variant no-infra-compute COLORS_PAR_PROVIDER_COMPUTE=no-infra
build_variant no-infra-smtp COLORS_PAR_PROVIDER_SMTP=no-infra
build_variant no-infra-dns COLORS_PAR_PROVIDER_DNS=no-infra
build_variant s3 COLORS_PAR_PROVIDER_BACKEND=s3
build_variant r2 COLORS_PAR_PROVIDER_BACKEND=r2

diff -qr "$root/green/src/resources/io/github/bigconfig-ai/once" "$root/red/resources"
diff -qr "$root/green/src/resources/io/github/bigconfig-ai/once" "$root/blue/src/package_once_blue/resources"

# The colours read YAML through three different parsers — yamlstar, Bun.YAML
# and PyYAML — so agreeing on the generated bytes is only half the contract.
# They also have to agree on what a scalar *means* before rendering starts.
scalars="$root/test/parity/scalars.yml"
(cd "$root/green" && bb ../scripts/scalars-green.clj "$scalars") >"$tmp/scalars-green"
(cd "$root/red" && bun ../scripts/scalars-red.ts "$scalars") >"$tmp/scalars-red"
(cd "$root/blue" && uv run python ../scripts/scalars-blue.py "$scalars") >"$tmp/scalars-blue"
diff "$tmp/scalars-green" "$tmp/scalars-red"
diff "$tmp/scalars-green" "$tmp/scalars-blue"

echo "green, red, and blue build artifacts are byte-identical"
echo "green, red, and blue agree on every scalar in the parity corpus"
