#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-once-blue", "blue"]
#
# [tool.uv.sources]
# package-once-blue = { git = "https://github.com/getcolors/once.git", rev = "c6f05a37000dd57329c41777ff32d90a093c7309", subdirectory = "blue" }
# blue = { git = "https://github.com/getcolors/blue.git", rev = "290f313ead5ca162875c33a049c880da017eae09" }
# ///
"""Thin launcher for package-once-blue."""
from package_once_blue import exec, run

__all__ = ["run"]

if __name__ == "__main__":
    exec()
